
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [9]:
import numpy as np
np_array = np.arange(10)
print(np_array)

[0 1 2 3 4 5 6 7 8 9]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [10]:
np_array = np.arange(9)
matrix = np_array.reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [11]:
element = matrix[1, 1]
print(element)

4


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [12]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# addition
add = array1 + array2
print("Addition:", add)

# Subtraction
subs = array1 - array2
print("Subtraction:", subs)

# Multiplication
mult = array1 * array2
print("Multiplication:", mult)

# Division
div = array1 / array2
print("Division:", div)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [13]:
array = np.array([1, 2, 3, 4, 5])

# sum
sum_array = np.sum(array)
print("Sum:", sum_array)

# mean
mean_array = np.mean(array)
print("Mean:", mean_array)

# standard deviation
std_array = np.std(array)
print("Standard Deviation:", std_array)

Sum: 15
Mean: 3.0
Standard Deviation: 1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [15]:
array = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = array.reshape(2, 3)

print(reshaped_array)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [16]:
np.random.seed(0)

random_array = np.random.randint(0, 100, size=(5, 5))

print(random_array)

[[44 47 64 67 67]
 [ 9 83 21 36 87]
 [70 88 88 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]]


Replace all values in the sub-array with a specific value.


In [19]:
replacement_value = 99

random_array[1:3, 1:3] = replacement_value

print(random_array)


[[44 47 64 67 67]
 [ 9 99 99 36 87]
 [70 99 99 12 58]
 [65 39 87 46 88]
 [81 37 25 77 72]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [ ]:
array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

sub_array = array[[1, 3], :]

print(sub_array)


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [ ]:
array_1d = np.array([0, 1, 2])

array_2d = np.tile(array_1d, (3, 1))

print(array_2d)

Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [ ]:
array_2d = np.tile(np.array([0, 1, 2]), (3, 1))

array_1d = np.array([1, 2, 3])

result = array_2d + array_1d

print("\n1D Array:")
print(array_1d)

print("\nResulting Array after Broadcasting:")
print(result)

# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [ ]:
np.random.seed(0)

array1 = np.random.randint(0, 100, size=(3, 3))
array2 = np.random.randint(0, 100, size=(3, 3))

print(array1)
print(array2)

concat_horizontally = np.hstack((array1, array2))
concat_vertically = np.vstack((array1, array2))


print(concat_horizontally)
print(concat_vertically)



split_horizontally = np.hsplit(concat_horizontally, 2)
split_vertically = np.vsplit(concat_vertically, 2)

print(split_horizontally[0])
print(split_horizontally[1])

print(split_vertically[0])
print(split_vertically[1])

# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [ ]:
array = np.array([1, 2, 1, 2, 3, 4, 5, 6, 8, 9, 1, 2, 2, 22, 21, 1, 1, 1, 1, 2, 5])

count_dict = {}

for element in array:
    if element in count_dict:
        count_dict[element] += 1
    else:
        count_dict[element] = 1

mode = max(count_dict, key=count_dict.get)
mode_count = count_dict[mode]

print("Array:", array)
print("Mode:", mode)
print("Count of Mode:", mode_count)

# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

